# Check on http://lint.travis-ci.org/ after modifying it!  Originally
# modified from https://gist.github.com/dan-blanchard/7045057
language: python
env:
  - PYTHON_VERSION=3.4
  - PYTHON_VERSION=3.3
  - PYTHON_VERSION=2.7 USE_CYTHON=TRUE
  - PYTHON_VERSION=2.7
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - wget http://repo.continuum.io/miniconda/Miniconda3-3.7.3-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  # Update conda itself
  - conda update --yes conda
install:
  - conda create --yes -n env_name python=$PYTHON_VERSION pip numpy scipy matplotlib pandas nose pep8 Sphinx=1.2.2 IPython
  - if [ ${USE_CYTHON} ]; then conda install --yes -n env_name cython; fi
  - source activate env_name
  - pip install sphinx-bootstrap-theme future six coveralls natsort pyflakes flake8 python-dateutil  decorator 'CacheControl[FileCache]' git+git://github.com/numpy/numpydoc.git
  - pip install -e . --no-deps
script:
  - PYTHONWARNINGS=ignore WITH_COVERAGE=TRUE make test
  - make -C doc clean html
after_success:
  - coveralls
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/9a439713959e710c7971
    on_success: change
    on_failure: always
