# Check on http://lint.travis-ci.org/ after modifying it!  Originally
# modified from https://gist.github.com/dan-blanchard/7045057
language: python
env:
  # Test against latest versions of numpy and matplotlib. Also test against
  # older versions of numpy and matplotlib (pre-1.4.0). matplotlib's boxplot
  # functionality was largely rewritten/refactored in 1.4.0 and some of skbio's
  # code had to be updated in the process, so it's worth testing against a
  # pre-1.4.0 version and whatever the latest version is.
  - PYTHON_VERSION=3.4 NUMPY_VERSION= MATPLOTLIB_VERSION=
  - PYTHON_VERSION=2.7 NUMPY_VERSION= MATPLOTLIB_VERSION= WITH_DOCTEST=True USE_CYTHON=TRUE
  - PYTHON_VERSION=2.7 NUMPY_VERSION='=1.7' MATPLOTLIB_VERSION='=1.3.1' WITH_DOCTEST=True
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - wget http://repo.continuum.io/miniconda/Miniconda3-3.7.3-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  # Update conda itself
  - conda update --yes conda
install:
  - conda create --yes -n env_name python=$PYTHON_VERSION pip numpy$NUMPY_VERSION scipy matplotlib$MATPLOTLIB_VERSION pandas nose pep8 Sphinx=1.2.2 IPython
  - if [ ${USE_CYTHON} ]; then conda install --yes -n env_name cython; fi
  - source activate env_name
  - pip install sphinx-bootstrap-theme future six coveralls natsort pyflakes flake8 python-dateutil
  - pip install -e . --no-deps
script:
  - if [ ${WITH_DOCTEST} ]; then PYTHONWARNINGS=ignore WITH_COVERAGE=TRUE make test; else PYTHONWARNINGS=ignore WITH_DOCTEST=FALSE WITH_COVERAGE=TRUE make test; fi
  - pushd doc
  - make clean
  - make html
  - popd
after_success:
  - coveralls
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/9a439713959e710c7971
    on_success: change
    on_failure: always
