# Check on http://lint.travis-ci.org/ after modifying it!  Originally
# modified from https://gist.github.com/dan-blanchard/7045057
language: python
env:
  # Test against latest versions of numpy and matplotlib. Also test against
  # older versions of numpy and matplotlib (pre-1.4.0). matplotlib's boxplot
  # functionality was largely rewritten/refactored in 1.4.0 and some of skbio's
  # code had to be updated in the process, so it's worth testing against a
  # pre-1.4.0 version and whatever the latest version is.
  - PYTHON_VERSION=3.4 NUMPY_VERSION= MATPLOTLIB_VERSION=
  - PYTHON_VERSION=2.7 NUMPY_VERSION= MATPLOTLIB_VERSION= WITH_DOCTEST=True USE_CYTHON=TRUE
  - PYTHON_VERSION=2.7 NUMPY_VERSION='=1.7' MATPLOTLIB_VERSION='=1.3.1' WITH_DOCTEST=True
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-2.2.2-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/anaconda/bin:$PATH
  # Update conda itself
  - conda update --yes conda
install:
  - conda create --yes -n env_name python=$PYTHON_VERSION pip numpy$NUMPY_VERSION scipy matplotlib$MATPLOTLIB_VERSION pandas nose pep8 Sphinx=1.2.2 IPython
  - if [ ${USE_CYTHON} ]; then conda install --yes -n env_name cython; fi
  - source activate env_name
  - pip install sphinx-bootstrap-theme future six coveralls natsort pyflakes flake8 python-dateutil
  - pip install -e . --no-deps
script:
  - if [ ${WITH_DOCTEST} ]; then PYTHONWARNINGS=ignore nosetests skbio --with-doctest --with-coverage -I DONOTIGNOREANYTHING; else PYTHONWARNINGS=ignore nosetests skbio --with-coverage -I DONOTIGNOREANYTHING; fi
  - pep8 skbio setup.py checklist.py
  - flake8 skbio setup.py checklist.py
  - ./checklist.py
  - pushd doc
  - make clean
  - make html
  - popd
after_success:
  - coveralls
