# Check on http://lint.travis-ci.org/ after modifying it!  Originally
# modified from https://gist.github.com/dan-blanchard/7045057
sudo: false
language: c
os:
  - linux
  - osx
env:
  - CONDA_PY=3.7 MAKE_DOC=TRUE
  - CONDA_PY=3.6 MAKE_DOC=TRUE
  - CONDA_PY=3.5 MAKE_DOC=TRUE USE_CYTHON=TRUE

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh; fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  # Update conda itself
  - conda update --yes conda

install:
  - conda create --yes -n env_name python=$CONDA_PY
  - conda install --yes -n env_name --file ci/conda_requirements.txt
  - if [ ${USE_CYTHON} ]; then conda install --yes -n env_name cython; fi
  - source activate env_name
  - conda info --envs
  - python --version
  - pip install -r ci/pip_requirements.txt
  - pip install . --no-deps

script:
  - WITH_COVERAGE=TRUE make test
  - if [ ${MAKE_DOC} ]; then make -C doc clean html; fi

after_success:
  - coveralls

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/9a439713959e710c7971
    on_success: change
    on_failure: always
