# Check on http://lint.travis-ci.org/ after modifying it!  Originally
# modified from https://gist.github.com/dan-blanchard/7045057
sudo: false
language: python
env:
  - PYTHON_VERSION=3.4 MAKE_DOC=TRUE
  - PYTHON_VERSION=3.3 USE_CYTHON=TRUE
  - PYTHON_VERSION=2.7
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - wget http://repo.continuum.io/miniconda/Miniconda3-3.7.3-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  # Update conda itself
  - conda update --yes conda
install:
  - conda create --yes -n env_name python=$PYTHON_VERSION --file ci/conda_requirements.txt
  - if [ ${USE_CYTHON} ]; then conda install --yes -n env_name cython; fi
  - source activate env_name
  - pip install -r ci/pip_requirements.txt
  - pip install . --no-deps
script:
  - WITH_COVERAGE=TRUE make test
  - if [ ${MAKE_DOC} ]; then make -C doc clean html; fi
after_success:
  - coveralls
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/9a439713959e710c7971
    on_success: change
    on_failure: always
